### ISSUE TITLE
Bugs in token-based light sources: no rotation, walls get offset

### ISSUE THREAD

**Issue by FoxLee** [caewok/fvtt-light-mask#10]
Firstly, thanks for accepting my feature request for token support! This is huge for me. However, there are a few quirks that could use attention if you have time.

The big issue is that the rotation setting seems to have no effect on token lights. No matter what I set it to, a regular polygon with four sides is fixed with its corners at the cardinal directions, so it always looks like a "diamond" rather than a "square". This seems to be true for all shapes, and rotating the token doesn't help either.

I had more luck making a square using walls. However, when I set the walls to move relative to the token, it offsets the mask southeast by about half a square. So in the example below, if I apply the walls on the left with the token in that position, I get the mask shown on the right.

![image](https://user-images.githubusercontent.com/10067730/170414786-8f53b22c-b65f-43ee-a5e7-fcd4fea5ec87.png)

I _can_ approximate the right mask by moving my walls in the opposite direction before caching, but the result is a bit janky, and frustrating to do every time.

(This is under the D&D 4e game system, with all other modules except libwrapper disabled.)

_Originally posted by @FoxLee in https://github.com/caewok/fvtt-light-mask/issues/4#issuecomment-1138136682_

**Comment by caewok** [comment]
Good catch about the shifting walls! I just fixed that in v0.3.6. As for the rotation, it seems like it is working for a Token in 4e.

Check to see if you are doing all of the following:

1. Double-click the token on the map to open the sheet. 
2. Click "Token" in the upper right bar. 
3. In the Token Configuration, select Light:Advanced Options.
4. Change the shape
5. Change the number of sides
6. Change the rotation angle. (Hint: Foundry won't let you edit the number box but if you click the little slider square, you can move it with the left/right arrow keys to get more precision than just dragging it with a mouse.)
7. Select Update Token.

My guess is that you are not hitting Update Token. Unlike with lights, Foundry's token lighting config does not do real-time updates (annoying, I know). So if you change the rotation angle, it may not look like it is doing anything until you save it.

If those steps don't work, please feel free to open a new issue and we can troubleshoot it. And if you have some other steps in mind that are not working as expected, maybe that should be a new issue too!

**Comment by FoxLee** [comment]
I was definitely pressing Update Token, but I'm pretty sure I was trying to work with prototype tokens in the previous example. (Which makes it more surprising that I got as far as I did. My guess is I may have unintentionally gone back and forth between prototypes and on-canvas tokens, hence getting some successes but failure overall.)

Either way, without updating anything I just tried it again on a fresh, on-canvas token and got exactly the expected results. So, as long as I handle prototypes by changing the settings on-canvas and then using "assign token", all is well. Thanks for your help!

If it's feasible to hide the advanced settings or provide a warning not to work on prototype tokens, that might save some confusion in the future. (Unless there is a warning and I just didn't notice?)

**Comment by caewok** [comment]
Yes, I was wondering if maybe you were in the prototype token. I was looking at that problem yesterday, and am still a bit puzzled as to why it is working for the token on the canvas but not for the prototype token. My hope is to release an update with a fix for the prototype token.
