### ISSUE TITLE
Inability to change token visibility state after changing its name

### ISSUE THREAD

**Issue by archeresky** [caewok/fvtt-light-mask#12]
**Description**
When the module is enabled it makes it impossible to change the token visibility state after its name was changed when the token was invisible. Confirmed with the module Find The Culprit that Light/Sound Mask is responsible for this.

**Steps to Reproduce**
- Place a token on the map
- Change visibility state to invisible
- Open the token menu and change its name
- Toggle visibility state
- Result: The visibility state cannot be toggled

**Versions**

    Module: 0.5.2
    dnd5e: 2.0.3
    Foundry: 10.290

**Additional info**
- Check attached video

[token bug.webm](https://user-images.githubusercontent.com/73297245/201956645-278b6c03-d43b-493d-b8e3-da4555141ea6.webm)

**Comment by caewok** [comment]
Thanks! Fixed in v0.6.0. Sort of took the long way round to address this, as I decided to improve how all the configurations were done.
