### ISSUE TITLE
Issue with prototype token

### ISSUE THREAD

**Issue by Korghen** [caewok/fvtt-light-mask#13]
With the last update of the module, I got an issue to update a prototype token. When I press the update button, the window don't close and i get this error:
TypeError: Cannot read properties of undefined (reading 'updateLightSource')
    at TokenConfig._updateObjectTokenConfig (patching.js:134:21)
    at async TokenConfig._onSubmit (foundry.js:5874:7)
_onSubmit @ foundry.js:5877
I tried with only this module activated (and libwrapper). There is no issue when the module is deactivated.

**Comment by caewok** [comment]
Should be resolved in v0.6.2.
