### ISSUE TITLE
Sound sources don't instantly activate/deactivate, icon doesn't change, defaults to 0 ft.

### ISSUE THREAD

**Issue by GambetTV** [caewok/fvtt-light-mask#15]
Noticing a lot of weird behavior in v0.7.2 of this module, with v11.308 of Foundry. Not sure if there wouldn't be an issue in other versions of Foundry, only just started playing with sound sources on the map.

Anyway, when drawing an Ambient Sound, regardless of how far I drag it, as soon as I release my mouse it brings up with Ambient Sound control configuration popup window, and the "Effect Radius" is always set to 0 feet. So if I need it to be the specific radius I had dragged it to, I now have to fiddle with this manually until it's the size I want, which is pretty strange behavior.

Then on top of this, right clicking should disable/enable the sound source, and it does, but it is no longer instantaneous to pushing the button anymore. Now, you must click the icon, and then move your mouse. Until you move your mouse, nothing happens. Worse, while simply moving your mouse is enough to activate/deactivate the sound, the icon will not turn red (for disabled) or white (for enabled) until you drag the mouse off the icon entirely.

The lights do not exhibit this behavior, by comparison, so the bug seems to only occur with sounds.

**Comment by caewok** [comment]
See also https://ptb.discord.com/channels/170995199584108546/722566083499786352/1149101337846489219

**Comment by GambetTV** [comment]
Sorry, you linked me to my own post in the Foundry Discord. Was there a response to my post there?

**Comment by caewok** [comment]
Should be fixed in v0.7.3. Thanks!
