### ISSUE TITLE
Sound Sources don't work with Token Attacher module, but Light Sources do

### ISSUE THREAD

**Issue by GambetTV** [caewok/fvtt-light-mask#17]
The module Token Attacher allows you to take a light source or a sound source (and a bunch of other things too) and "attach" them to a token, so that they will move as the token moves. Your module seems perfectly compatible with Token Attacher when it comes to Light Sources, but for some reason with Sound Sources, your module causes them to get stuck, and they won't move until you go back into the Ambient Sound Controls, at which point it snaps back to the token.

**Comment by caewok** [comment]
I think I resolved this in v0.7.4.

**Comment by GambetTV** [comment]
Nope, still broken, unfortunately. Behavior is exactly the same as described above, in fact.

**Comment by GambetTV** [comment]
Okay I may have figured something important out. You also need the module "Select Tool Everywhere." This allows you to actively select things like sound effects and light sources, which you can't do without it. I do have this module installed, I just forgot to mention it in my github issue, my fault for that!

Modules Active: Libwrapper, Light/Mask, Token Attacher, Select Tool Everywhere
Step 1: Click on Ambient Sound Controls, Draw Ambient Sound, Drag on the scene to create an Ambient Sound, and put an audio file in the source file path. 
Step 2: Put a token on the map. With the token selected, click on (TA) Open attaching UI under token controls, which brings up more controls for the token attacher on that token.
Step 3: Click back on Ambient Sound Controls, so you can see your Ambient Sound on the map. Drag it on top of the token.
Step 4: With the Ambient Audio selected, Click on "Attach selected elements" in the TA controls you opened up.
Step 5: Move the token around, and notice how the audio does not move with them. If you go back to the Ambient Sound Controls, the sound effect will immediately snap back to the token, it just won't follow it otherwise.
Step 6: Do the above 5 steps, but make a light source instead of a sound source and watch it work perfectly. Obviously there's something different in how your module treats sound effects and light effects as it interacts with the other two modules.

**Comment by caewok** [comment]
I think I got it this time! v0.7.5.
