### ISSUE TITLE
Cached walls seem to block sight.

### ISSUE THREAD

**Issue by TheXeno30** [caewok/fvtt-light-mask#19]
Fantastic module!!! Been looking for this for a long time :) 

I want to make the sun fall in when you open the door.
![image](https://github.com/user-attachments/assets/36789e0a-23f5-451c-b2b4-cdbd3672a8f0)

so i created this shape
![image](https://github.com/user-attachments/assets/b9e6f92d-5f1d-4ea3-b2ed-78cdba86df46)

But when i add it to the room it blocks the sight of the tokens
![image](https://github.com/user-attachments/assets/4180e236-1bf6-4791-a95b-e5a7a08c1b86)
![image](https://github.com/user-attachments/assets/6bf9d39d-3c6d-454b-9659-175346c30641)
![image](https://github.com/user-attachments/assets/c06b33e8-c17f-4410-905f-3753c0f6627c)

A regional area is in effect also inside the room to dim the light from the global lighting and there is a roof that restrict light. Neither should effect the light.

Don't know if i'm doing anything wrong or if its a bug. 

Chrome
V12
D&D 3.3.1.

**Comment by TheXeno30** [comment]
Anything for this yet? it would be a lifesaver for ppl using levels :)

**Comment by caewok** [comment]
This is a Levels issue. I don't think I can fix it. Levels should not be treating the cached edge as a wall.
