### ISSUE TITLE
BUG: Clashes with Splatter module

### ISSUE THREAD

**Issue by GambetTV** [caewok/fvtt-light-mask#5]
When this module is active, the module "Splatter" which creates blood effects on tokens and on the map, the Splatter module does not function at all. Disabling this module fixes it.

**Comment by MrPotatoZed** [comment]
I'm seeing the same behavior. FTC points at light mask and disabling light mask fixes the issue. When damage is applied that should cause splatters I see the following error: 
![image](https://user-images.githubusercontent.com/85974617/156065229-dbe6fc21-a423-4e04-b598-4561110f8736.png)

This has been reported to ripper as well. Any assistance would be appreciated. V9.249, 5e 1.5.7, splatter 2.9.4., light mask .1.2.

**Comment by caewok** [comment]
I believe this module now works with Splatter. I didn't check 0.1.2, but appears to work with 0.2.0.
