### ISSUE TITLE
Incompatible with Perfect Vision

### ISSUE THREAD

**Issue by dev7355608** [caewok/fvtt-light-mask#7]
As of v0.2.0 Perfect Vision and Light Mask are incompatible, because Perfect Vision includes the standard integer version of Clipper and Light Mask the float version.

**Comment by caewok** [comment]
Interesting. I should be able to import clipper some different way to avoid that incompatibility. I will look into it.

**Comment by caewok** [comment]
Fixed in 0.2.2.
