### ISSUE TITLE
Recent issue with levels/wall height module

### ISSUE THREAD

**Issue by NdranC** [caewok/fvtt-light-mask#9]
After a recent update I noticed all lights are going through walls if they are configured with a height in the levels module. Using "Find the Culprit" I tracked the issue to this module. If disabled everything behaves as expected.

To replicate in a new world,

1. Enable Better Roofs, Levels, libWrapper, Light/Sound Mask, Wall Height.
2. Draw a light and a wall right next to it so it can cast a shadow
3. Move the light around the wall to confirm the shadow is cast correctly
4. Add a height of 0 to 9 to both the light and wall
5. Attempting to move or update the light after this will make the light ignore the wall as if it wasn't there
6. Disabling Light/Sound Mask and attempting this again should solve the issue and the wall will always cast a shadow correctly.

I'm unsure if this is necessarily something wrong on your end but it was working fine last week. So it must have been a recent update.

Thanks for your time.

**Comment by dev7355608** [comment]
Wall Height adds `t` and `b` (top and bottom range) to `origin`, but Light Mask overrides `origin`:
https://github.com/caewok/fvtt-light-mask/blob/723c5e2c66d1235c29056558b7ef94928041cb51/scripts/ClockwiseSweep/LightMaskClockwisePolygonSweep.js#L129

**Comment by caewok** [comment]
Thanks for the tip about overwriting origin! I believe v0.3.1 addresses this issue, but please re-open if the problem persists.
